### ISSUE TITLE
is the non-lead node able to response pure query request ?

### ISSUE THREAD

**Issue by changloong** [canonical/dqlite#160]
If I need do some query, which not need strict consistency.  will the non-leader node be able to run this kind sql ? (to reduce the leader task load)

**Comment by changloong** [comment]
please help me by suggestion where I can start to add this function ?  Thanks in advance.

**Comment by freeekanayaka** [comment]
The quickest way would probably be to relax the checks in ```src/gateway.c``` and add some configuration option which skips the check of the node being the leader.

**Comment by changloong** [comment]
Thanks for the explain. 

I find the sqlite has the api to allow open it as READ ONLY connection, If I open the dqlite db file in other process with original sqlite, will it working on leader and non-leader node ?

I plan to run some select query will cost some CPU time, and the results don't need to be always correct in my case.

**Comment by freeekanayaka** [comment]
It might work (but you'll have to pass to ```sqlite3_open_v3``` the name of the VFS that dqlite uses internally, see the code).

However, you should not do it because it will be unsafe: dqlite assumes that nothing else is accessing the database on non-leader nodes, this is required in order for internal WAL checkpoints to work properly.

If you are absolutely sure that no write transaction is going to be executed on the leader while you perform the unsafe read query on the follower, you might go for it, but it feels something that is very difficult to guarantee. To the least you'll have to put in place some distributed locking mechanism.

I recommend that you first try to perform your read queries normally, on the leader, and then come back to this issue only if you notice that this is an actual performance problem for your workload. Or alternatively show me some back of the envelope calculations that indicate that you will likely hit a performance issue. With that information at hand we can try to understand what's the best option for you.

**Comment by changloong** [comment]
hi @freeekanayaka 

Thanks for the explain.

> I recommend that you first try to perform your read queries normally, on the leader, and then come back to this issue only if you notice that this is an actual performance problem for your workload.

I intend to use DQLITE cross cloud region,  if I pass all read queries into leader. the response will be slow and cost a lot extra traffic fee.  

I look at the solution from Bedrock,  Bedrock run read in local node,  and return a global commit id(version),  user can use this commit id to detect write conflict late.

Bedrock also provide a flexible consensus control,  user exchange the write response speed from reliability. (for example user add a comment into article, only require one node confirm).

I think by add a global version into DQLITE, and allow read from Raft node local will be a nice selling point.

**Comment by freeekanayaka** [comment]
> hi @freeekanayaka
> 
> Thanks for the explain.
> 
> > I recommend that you first try to perform your read queries normally, on the leader, and then come back to this issue only if you notice that this is an actual performance problem for your workload.
> 
> I intend to use DQLITE cross cloud region, if I pass all read queries into leader. the response will be slow and cost a lot extra traffic fee.

I would not recommend using dqlite on a non-colocated setup (e.g. WAN). And as far as I know bedrock too was not used in that scenario. You might want to have a look at cockroachdb, which is explicitly designed for geographically distributed replication.

> I look at the solution from Bedrock, Bedrock run read in local node, and return a global commit id(version), user can use this commit id to detect write conflict late.
> 
> Bedrock also provide a flexible consensus control, user exchange the write response speed from reliability. (for example user add a comment into article, only require one node confirm).
> 
> I think by add a global version into DQLITE, and allow read from Raft node local will be a nice selling point.

Yes, that's something valuable I'd like to work on, but the company can't put resources on it at the moment.

**Comment by changloong** [comment]
Thanks for the `cockroachdb` advise, I will looking into it.

`bedrock` has 6 server at 3 region,  each region has 2 server. With this setup they are able to provide fast write with 1 vote confirm by the server located at the master node region. 

Each region has a group application server like PHP,  configured to execute query on local node first.   and each node only forward write query into master.

**Comment by changloong** [comment]
hi @freeekanayaka 

I check the VFS and find the lock is not implement,  Is the DQLITE db instance only be able to work in the loop thread ? 

The `raft_last_applied` is never duplicate cross process life time ? (I want to use it as cache version)

If I run a read query on `leader-> conn ` from the loop thread,   non leader node, is this code work?
```c
void do_non_leader_reader(leader* l){
    int raft_state = raft_state(l->raft);
    assert(  raft_state!= RAFT_LEADER);
    l->raft->state = RAFT_LEADER;
    sqlite3_stmt *stmt;
    int version_id = raft_last_applied(l->raft);
    int rc = sqlite3_prepare_v2(l->conn, "SELECT * from users where id=1", -1, &stmt, 0);   
    assert(rc == SQLITE_OK);
    rc = sqlite3_step(stmt);
    assert(rc == SQLITE_ROW);
    sqlite3_finalize(stmt);
    l->raft->state = raft_state;
}
```

I already has my app with exists code operate on normal sqlite,  I like to keep some database without replication by skip `vfsInit` and `sqlite3_wal_replication_register`,   with WAL mode.  If I link with DQLITE it will continue to work ?

Is Dqlite able to handle GB level database?  

Thanks in advance.

**Comment by changloong** [comment]
https://github.com/canonical/dqlite/blob/master/src/vfs.c#L734
this should be ?
```c
assert( (offset  + amount) <= (int)f->content->page_size);
```

**Comment by freeekanayaka** [comment]
> https://github.com/canonical/dqlite/blob/master/src/vfs.c#L734
> this should be ?
> 
> ```c
> assert( (offset  + amount) <= f->content->page_size);
> ```

Yes, this tighter version of the assertion should hold as well. Why do you care? Are you just trying to understand that code?

**Comment by freeekanayaka** [comment]
> hi @freeekanayaka
> 
> I check the VFS and find the lock is not implement, Is the DQLITE db instance only be able to work in the loop thread ?

Yes. Dqlite is single-threaded and uses no locks. Therefore anything done outside the loop thread is unsafe.

> 
> The `raft_last_applied` is never duplicate cross process life time ? (I want to use it as cache version)

I don't understand this question.

> If I run a read query on `leader-> conn ` from the loop thread, non leader node, is this code work?
> 
> ```c
> void do_non_leader_reader(leader* l){
>     int raft_state = raft_state(l->raft);
>     assert(  raft_state!= RAFT_LEADER);
>     l->raft->state = RAFT_LEADER;
>     sqlite3_stmt *stmt;
>     int version_id = raft_last_applied(l->raft);
>     int rc = sqlite3_prepare_v2(l->conn, "SELECT * from users where id=1", -1, &stmt, 0);   
>     assert(rc == SQLITE_OK);
>     rc = sqlite3_step(stmt);
>     assert(rc == SQLITE_ROW);
>     sqlite3_finalize(stmt);
>     l->raft->state = raft_state;
> }
> ```

If you are **absolutely** sure that you're ```sqlite3_prepare/sqlite3_step``` calls will not trigger a database write (i.e. the query is 100% read only), then yes, it should be fine to call ```sqlite3_prepare/sqlite3_step``` from the loop thread, with the ```l->conn``` leader connection, or even a different connection that you open yourself.

However beware that you'll need to complete the query all at once (i.e. call ```sqlite3_step``` multiple times until it returns ```SQLITE_DONE```). You can't leave the query pending and resume it later (as it's done normally by dqlite for large queries), because that would leave a read transaction open on that follower which would prevent the follower from applying a checkpoint command coming from the leader.

In theory you don't need to run ```l->raft->state = RAFT_LEADER```, if your query is 100% read only, then raft is not involved. But maybe have added it because of additional checks that I might not recall right now. Try to remove it, and just let me know what does not work.

I don't understand why you need:

```
int version_id = raft_last_applied(l->raft);
```

as it seems you're not using it.

> I already has my app with exists code operate on normal sqlite, I like to keep some database without replication by skip `vfsInit` and `sqlite3_wal_replication_register`, with WAL mode. If I link with DQLITE it will continue to work ?

It will work. You can use normal SQLite from another thread using a separate database. Just be sure that you set ```SQLITE_CONFIG_MULTITHREAD``` using ```sqlite3_config```. That should already be the default if you are not using the ```go-dqlite``` bindings. However if you do use the ```go-dqlite``` bindings you'll need to call it. See also https://godoc.org/github.com/canonical/go-dqlite#ConfigMultiThread.

> 
> Is Dqlite able to handle GB level database?

There's no limit in the size of the database. However you must have enough memory to hold it completely in RAM, since raft keeps its entire state machine in memory (the state machine is the database in this case).

**Comment by changloong** [comment]
> Yes, this tighter version of the assertion should hold as well. Why do you care? Are you just trying to understand that code?

Yes, I just try read the code.

> " The raft_last_applied is never duplicate cross process life time ? (I want to use it as cache version)"
> I don't understand this question.

I mean if I stop  all node, and restart again.  will this number duplicate with  last process life value?

> I don't understand why you need:

You are right, that is not used in this case.

> If you are absolutely sure that you're sqlite3_prepare/sqlite3_step calls will not trigger a database write (i.e. the query is 100% read only), then yes, it should be fine to call sqlite3_prepare/sqlite3_step from the loop thread, with the l->conn leader connection, or even a different connection that you open yourself.

>However beware that you'll need to complete the query all at once (i.e. call sqlite3_step multiple times until it returns SQLITE_DONE). You can't leave the query pending and resume it later (as it's done normally by dqlite for large queries), because that would leave a read transaction open on that follower which would prevent the follower from applying a checkpoint command coming from the leader.

Will  `sqlite3_reset` and ` sqlite3_clear_bindings` remove the read transaction? so I can reuse the sqlite3_stmt without prepare for every api call ? (I plan to destroy sqlite3_stmt when node member ship changed, or after schema change).

When I start read on the non leader node,  cloud it happen in the process of applying a checkpoint? (Maybe checkpoint started and call co_switch to allow the loop have chance accept api call, or it will be done at once without co_switch?)

I plan add an extra status to trigger error from the VFS write operate, before I start readonly query, and remove it when I finished.


> In theory you don't need to run l->raft->state = RAFT_LEADER, if your query is 100% read only, then raft is not involved. But maybe have added it because of additional checks that I might not recall right now. Try to remove it, and just let me know what does not work.

I think read should not trigger methodBegin from here : https://github.com/canonical/dqlite/blob/master/src/replication.c#L383

I will do more test on real code and let you know the results.

> It will work. You can use normal SQLite from another thread using a separate database. Just be sure that you set SQLITE_CONFIG_MULTITHREAD using sqlite3_config. 

I am not use go and I am plan use it without SQLITE_CONFIG_MULTITHREAD,  I will make sure any database instance will only open once and read/write on same thread.  If i need multi thread read I will enable SQLITE_CONFIG_MULTITHREAD.

this new non-raft db instance will create normal `file.db3` and `file.wal`, so safe copy to run at other server with normal sqlite ?

> There's no limit in the size of the database. However you must have enough memory to hold it completely in RAM, since raft keeps its entire state machine in memory (the state machine is the database in this case).

Thanks for all this tips, I am appreciate to this very nice and quick response:)

**Comment by freeekanayaka** [comment]
> > " The raft_last_applied is never duplicate cross process life time ? (I want to use it as cache version)"
> > I don't understand this question.
> 
> I mean if I stop all node, and restart again. will this number duplicate with last process life value?

It **eventually** will, but two things need to happen before that: 1) a leader is elected 2) the leader makes a couple or more rounds of heartbeats so it get to know the progress of followers and followers get to know the last committed index. After all that happens, yes, it will return the last value you had before the restart (unless new transactions where committed in the meantime).
 
> > If you are absolutely sure that you're sqlite3_prepare/sqlite3_step calls will not trigger a database write (i.e. the query is 100% read only), then yes, it should be fine to call sqlite3_prepare/sqlite3_step from the loop thread, with the l->conn leader connection, or even a different connection that you open yourself.
> 
> > However beware that you'll need to complete the query all at once (i.e. call sqlite3_step multiple times until it returns SQLITE_DONE). You can't leave the query pending and resume it later (as it's done normally by dqlite for large queries), because that would leave a read transaction open on that follower which would prevent the follower from applying a checkpoint command coming from the leader.
> 
> Will `sqlite3_reset` and ` sqlite3_clear_bindings` remove the read transaction? so I can reuse the sqlite3_stmt without prepare for every api call ? (I plan to destroy sqlite3_stmt when node member ship changed, or after schema change).

Yes, if you call `sqlite3_reset` and `slite3_clear_bindings` the read transaction will be terminate, and you can re-use the `sqlite3_stmt` object later on without preparing it again (as long as the schema hasn't changed, as you mention).
 
> When I start read on the non leader node, cloud it happen in the process of applying a checkpoint? (Maybe checkpoint started and call co_switch to allow the loop have chance accept api call, or it will be done at once without co_switch?)

It can't happen that you are in the middle of checkpoint. The checkpoint operation is synchronous and does not use co_switch. See the `apply_checkpoint` function in `fsm.c`, which is called by both leader and followers when a checkpoint command is committed.
 
> I plan add an extra status to trigger error from the VFS write operate, before I start readonly query, and remove it when I finished.

That won't work because the VFS code will be called **after** the frames command has been committed to the raft log. So you'll probably need to do that trick in the replication hooks, e.g. in the `methodBegin` function of `replication.c`, which is called right when a write transaction is started (before the VFS write).

> > In theory you don't need to run l->raft->state = RAFT_LEADER, if your query is 100% read only, then raft is not involved. But maybe have added it because of additional checks that I might not recall right now. Try to remove it, and just let me know what does not work.
> 
> I think read should not trigger methodBegin from here : https://github.com/canonical/dqlite/blob/master/src/replication.c#L383

Exactly, that's basically what I was saying right above. It seems that this check/trick is already in place and maybe you don't have to add anything more.

> I will do more test on real code and let you know the results.

Sounds good.

> > It will work. You can use normal SQLite from another thread using a separate database. Just be sure that you set SQLITE_CONFIG_MULTITHREAD using sqlite3_config.
> 
> I am not use go and I am plan use it without SQLITE_CONFIG_MULTITHREAD, I will make sure any database instance will only open once and read/write on same thread. If i need multi thread read I will enable SQLITE_CONFIG_MULTITHREAD.

If you are not using Go, and you don't want to call SQLite from a different thread, then you should call `sqlite3_config(SQLITE_CONFIG_SINGLETHREAD)` at the beginning of your process. That should make everything faster, since no OS locks will be used internally by SQLite.

If you are not using Go, how are you going to use dqlite? Are you writing a client in another language or you planning to somehow plug directly into the dqlite internals without using the network layer?

If you can share a bit more about your architecture, I might be able to give hints. If you can't share, that's ok.

> this new non-raft db instance will create normal `file.db3` and `file.wal`, so safe copy to run at other server with normal sqlite ?
> 
Yes, your regular SQLite database file (plus possibly `.wal`) will be 100% a normal SQLite file, and you can do whatever you want with it.

> > There's no limit in the size of the database. However you must have enough memory to hold it completely in RAM, since raft keeps its entire state machine in memory (the state machine is the database in this case).
> 
> Thanks for all this tips, I am appreciate to this very nice and quick response:)

You're welcome, thanks for the interesting questions too :)

**Comment by changloong** [comment]
> If you are not using Go, and you don't want to call SQLite from a different thread, then you should call sqlite3_config(SQLITE_CONFIG_SINGLETHREAD) at the beginning of your process. That should make everything faster, since no OS locks will be used internally by SQLite.

> If you are not using Go, how are you going to use dqlite? Are you writing a client in another language or you planning to somehow plug directly into the dqlite internals without using the network layer?

I am build my service on [Dlang](https://dlang.org/) & libuv,  right I am build SQLITE without lock enable mmap. It has great performance(like 200K/s cached http request).   I am explore my options to add distributed options. 

After some compare, I think better to start with DQLITE, since it will allow me do minimal code change.  And I have confidence it will work great.   

Right now my service still work on single thread. Late I plan to add  multi libuv loop with multi thread,  and some of them use DQlite, some use SQLITE (or one write thread, multi read thread with LOCK).   I am able to delegate a task to run on a specified thread,  from my api entry thread,  use message pass without lock.

**Comment by freeekanayaka** [comment]
> > If you are not using Go, and you don't want to call SQLite from a different thread, then you should call sqlite3_config(SQLITE_CONFIG_SINGLETHREAD) at the beginning of your process. That should make everything faster, since no OS locks will be used internally by SQLite.
> 
> > If you are not using Go, how are you going to use dqlite? Are you writing a client in another language or you planning to somehow plug directly into the dqlite internals without using the network layer?
> 
> I am build my service on [Dlang](https://dlang.org/) & libuv, right now I am build SQLITE without lock and enable mmap. It has great performance(like 200K/s cached http request). I am exploring my options to add distributed options.
> 
> After some compare, I think better to start with DQLITE, since it will allow me do minimal code change. And I have confidence it will work great.
> 
> Right now my service still work on single thread. Late I plan to add multi libuv loop with multi thread, and some of them use DQlite, some use SQLITE (or one write thread, multi read thread with LOCK). I am able to delegate a task to run on a specified thread, from my api entry thread, use message pass without lock.

That's interesting. If you hit any issue, let me know and I'll try to fix them.

The only issue that I see (apart from performing read-only transactions on followers, which is something I didn't experiment with so far), is that if you perform disk I/O with regular SQLite, that will block your uv loop. Depending how much time it remains blocked, it could be a problem (for example the leader might not be able to send heartbeats in time and lose leadership). You can tweak the dqlite/raft timeouts, with `dqlite_set_network_latency`, and I recommend to do that so you don't end up with an unstable cluster.

**Comment by freeekanayaka** [comment]
Also, how are you going to do with the dqlite client? Will you need to write a Dlang client for dqlite?

**Comment by changloong** [comment]
If api need write into database, I just forward api into leader, and exec native sqlite c api on leader. will this work on leader ?

**Comment by freeekanayaka** [comment]
> If api need write into database, I just forward api into leader, and exec native sqlite c api on leader. will this work on leader ?

In principle, yes. In practice you'll have to basically re-invent a little bit of dqlite internals. You should do basically what it's done in `gateway.c` when handling a single exec request: you need to invoke `leader__exec` from `leader.c` and wait for the given callback to fire. Or alternatively call `sqlite3_step` directly in a coroutine, like it's done in `leader.c` (see below).

My long term plan would be to make it much easier to do what you want, but for now the way you are supposed to interact with dqlite is using its network API.

> 
> Use wire protocol will need I rebase a lot code, If I can make it work I will avoid to implement it in Dlang. If native sqlite api write not work on leader, I will try some workaround method first.

If you are fine using coroutines, you might be able to not rewrite your code, but you need to basically execute all your SQLite code in some coroutine, and be aware that every time you call `sqlite3_step` for a write transaction your coroutine will be suspended and needs to be resumed later.

You'll surely need to fork dqlite and modify its internal so you can basically re-use its engine, but plugging your own flow control. As I said above, supporting this kind of use is in my long term plan, but I can't do it at the moment.

**Comment by changloong** [comment]
Thanks for share your plan and explain the details.

I am not to expect SQLITE to implement this soon.  My code base already work with coroutines,   so I just need to modify it to work with leader and barrier.

**Comment by freeekanayaka** [comment]
> My code base already work with coroutines, so I just need to modify it to work with leader and barrier.

That's a good start then. It might be possible without too much troubles, but as said you'll very likely need to fork dqlite. I'm happy to merge any compatible change that might help you.

I like your design, it's actually the design I would recommend everybody to use. But dqlite was born with a slightly different use case, so it has a network API. In the future I'd like to make it as easy as possible to use your design.

**Comment by changloong** [comment]
Sure, I will request merge back if the some things is useful I come up.  I need to replace LIBCO with D fiber,  it will not compatible with DQLITE code base.

**Comment by changloong** [comment]
Hi @freeekanayaka,

I just realize on SQLITE there is no transactions isolation for one connection.  in this case a read start after write transaction and finish before write transaction submitted, It will return dirty value could be rollback late.  I can not think of a simple solution to deal with this.

I guess DQLITE will not support 2 connection in one thread for same VFS database ?  (I am not sure  lock is required or not), this seems is the only way to get transaction isolation.

I am thinks of just replication write transaction operate. (sqlite3_expert_sql with bind values and sqlite3_step count, or sqlite3_expanded_sql).    In this case I can use origin sqlite with write/read  isolation connection. and also the raft entry log size is reduced.  

My current code execute atomic write,  alway finished before other read start.  don't have this problem.

**Comment by freeekanayaka** [comment]
> I guess DQLITE will not support 2 connection in one thread for same VFS database ? (I am not sure lock is required or not), this seems is the only way to get transaction isolation.

You can do that. Dqlite supports one writer with concurrent readers. You can create another leader connection and perform your read with that: it will be isolated from any ongoing write transaction and won't read uncommitted data.

**Comment by freeekanayaka** [comment]
(of course concurrent readers must be run from the uv loop thread)

**Comment by changloong** [comment]
OK, I will create read-only connection on raft leader node.  use that in loop thread only.

If I understand it correct,  the follower node don't need open read-only connection.  I guess the WAL append and checkpoint is finished in one operate(on read can execute in the process).

**Comment by freeekanayaka** [comment]
> OK, I will create read-only connection on raft leader node. use that in loop thread only.
> 
> If I understand it correct, the follower node don't need open read-only connection. I guess the WAL append and checkpoint is finished in one operate(on read can execute in the process).

I'm not sure to understand your question here.

You can open any amount of SQLite connections on both the leader and the follower. If you open the connection with `SQLITE_OPEN_READONLY` as flag and you pass the dqlite's VFS name, that should be safe (because you'll never enter a write transaction, and the raft hooks won't be called at all), as long as you don't "pause" queries, i.e. you call `sqlite3_step()` until it returns `SQLITE_DONE` or you call `sqlite3_reset`.

**Comment by changloong** [comment]
Thanks for the explain. 

Is multi DQLITE instance can run in one loop thread ?  (I see there is some argument pass to libco by global var, maybe can cause problem).    

If I use canonical raft as key-value cache,  can I run multi raft instance in one loop ?

**Comment by freeekanayaka** [comment]
> Thanks for the explain.
> 
> Is multi DQLITE instance can run in one loop thread ? (I see there is some argument pass to libco by global var, maybe can cause problem).
> 

If I understand your question correctly, you're asking if you can run multiple instances of the dqlite engine in a single libuv loop.

First of all, why do you need to do that?

I think it should work, those global variables are safe because they are basically just holding a value temporary while switching between coroutines, they won't create races.

> If I use canonical raft as key-value cache, can I run multi raft instance in one loop ?

I don't understand exactly what you mean by key-value cache, but yes you can run multiple raft instances in one loop.

Again, I'm not sure why you'd want to do that. In general, the use case of multi-raft is to have multiple replication groups, but that's a pretty sophisticated setup. Care to elaborate your use case and requirements?

**Comment by changloong** [comment]
> First of all, why do you need to do that?

To increase the throughput with database shard.

> I think it should work, those global variables are safe because they are basically just holding a value temporary while switching between coroutines, they won't create races.

Great to know  DQLITE is capable to do this.

> I don't understand exactly what you mean by key-value cache, but yes you can run multiple raft instances in one loop.
> Again, I'm not sure why you'd want to do that. In general, the use case of multi-raft is to have multiple replication groups, but that's a pretty sophisticated setup. Care to elaborate your use case and requirements?

To add a distribute cache layer, this will avoid send 4K WAL page.   

With sqlite3 write,  the raft can not do pipeline optimization because one transaction could depend on previous one.  A key-value cache leader can send request without wait the follower previous response.

**Comment by freeekanayaka** [comment]
> > I don't understand exactly what you mean by key-value cache, but yes you can run multiple raft instances in one loop.
> > Again, I'm not sure why you'd want to do that. In general, the use case of multi-raft is to have multiple replication groups, but that's a pretty sophisticated setup. Care to elaborate your use case and requirements?
> 
> To add a distribute cache layer, this will avoid send 4K WAL page.
> 
> With sqlite3 write, the raft can not do pipeline optimization because one transaction could depend on previous one. A key-value cache leader can send request without wait the follower previous response.

Correct, pipeline is not possible indeed. However I don't see how a cache can solve this: don't you risk to respond to a client before a committed transaction is actually safely replicated to a quorum of followers?

I probably don't understand the design you have in mind.
