### ISSUE TITLE
Question: Any plans for a cross platform library

### ISSUE THREAD

**Issue by zbalkan** [canonical/dqlite#168]
Is there any plan for having a cross-platform dsqlite?

We know that libuv and SQLite is cross/multi platform. Yet, C-raft and libco are Linux only libraries. Is there a future plan to replace them with cross-platform equivalences -existing or newly created?

**Comment by freeekanayaka** [comment]
libco should already be multiplatform, at least to a certain extent: although I never tested it I see that it has some [support](https://github.com/canonical/libco/blob/master/fiber.c) for Windows.

For libraft the only bit that is Linux-specific is the asynchronous file I/O used [here](https://github.com/canonical/raft/blob/master/src/uv_file.c). I'm currently not planning to add support for other platform, but it shouldn't be too difficult to do so, since the code involved is pretty limited. I'm happy to accept patches in that regard, or you could contact Canonical if you wish to have that done for you.

**Comment by freeekanayaka** [comment]
FYI I'm planning to modify C-raft to add support for the new ```io_uring``` asynchronous file I/O API that was recently added to the Linux kernel. That will likely force me to generalize the code in ```uv_file.c``` a little bit and at that point adding a third system specific backend (e.g. Window or macOS) might be easier. I'm not sure what the timeline of this will be as it's not a priority at the moment, so YMMV.

**Comment by zbalkan** [comment]
Since `io_uring` is Linux-dependent, wouldn't that make things harder for multi-platform support? I mean you are already doing a great job with `libuv` in that context. Do you plan to move away from `libuv` or just to enhance the I/O features?

**Comment by freeekanayaka** [comment]
@zbalkan the idea is to decouple the implementation of ```uv_file.c``` from the specific APIs that the underlying OS offers for performing asynchronous file I/O. So the logic in ```uv_file.c``` would only use ```libuv``` API (which are cross platform) plus some new raft-internal abstraction that would wrap the underlying OS APIs and whose implementation would be changed at compile time according to the environment that ```configure``` detects. That way if you want to add support for a new OS there would be no need to modify ```uv_file.c``` at all, but just to implement the internal raft wrappers (which would live in something like ```uv_os_unix.c```, ```ov_os_windows.c```, etc).

Hope that's clear.

**Comment by zbalkan** [comment]
That clear indeed. Thanks.

**Comment by stgraber** [comment]
We've been merging some support for other platforms (BSD/MacOS) and will be happy to keep doing so.
For the client, we've got an issue at #291 now which should similarly not be platform-specific.
