### ISSUE TITLE
understanding Node ID

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#171]
I'm trying to understand the use and importance of node ID.  Two observations I have that I'd like a bit clarification on are:

1. Nodes started with 1 seems to be special in that they are automatically a leader.  So I assume 1 is a special value.  Is the accepted way to build a cluster be to always start with ID 1 and then add nodes to that master.

2. In go-dqlite the sqlite based NodeStore does not seem to respect IDs.  This is what threw me off and makes me question if ID is really important at all and used by dqlite internals.  So what is the purpose of the NodeID?

**Comment by freeekanayaka** [comment]
Yeah ID 1 is some sort of special value. The idea is that you start the first node with ID 1, and then you use ```client.Client.Add()``` and ```client.Client.Remove()``` to grow/shrink nodes. Once you have more than one node, you can remove any node at any time, including the node with ID 1. The only constraint is that ID must be unique and must not be re-used.

You're right, the NodeStore currently is used only by clients in order to find servers that belong to the cluster and the ID is not really used nor respected. I initially wanted to use the NodeStore interface also for internal cluster membership bookkeeping, but things changed. I need to give it another look and possibly just decide to remove IDs from the NodeStore entirely.

**Comment by ibuildthecloud** [comment]
Thanks, make sense.
