### ISSUE TITLE
Works on Xenial, fails on Bionic

### ISSUE THREAD

**Issue by paulstuart** [canonical/dqlite#187]
I'm running into issues with dqlite (actually dqlite-demo but I believe it's a dqlite issue at the core).

This is using the packages from `ppa:dqlite/stable`, as well as building from source (latest versions).

It appears to fail during the capabilities probe:

`
openat(AT_FDCWD, "/tmp/dqlite-demo/1/.probe-2ZN7v3", O_RDWR|O_CREAT|O_EXCL, 0600) = 9
fallocate(9, 0, 0, 4096)                = 0
unlink("/tmp/dqlite-demo/1/.probe-2ZN7v3") = 0
fcntl(9, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
fcntl(9, F_SETFL, O_RDWR|O_DIRECT|O_LARGEFILE) = 0
write(9, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 4096) = 4096
io_setup(1, [0x7fc25ef7d000])           = 0
io_submit(0x7fc25ef7d000, 1, [{aio_lio_opcode=IOCB_CMD_PWRITE, aio_fildes=9, aio_buf="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., aio_nbytes=4096, aio_offset=0}]) = -1 EINVAL (Invalid argument)
io_destroy(0x7fc25ef7d000)              = 0
`

Testing is in simple docker containers that vary only in the release used  for the image base (`ubuntu:xenial` vs. `ubuntu:bionic`)

**Comment by freeekanayaka** [comment]
A few questions:

1. What kernel version is the host running?

2. The docker containers use different versions of the deb? IOW does the ```ubuntu:xenial``` container use the xenial version of the deb and the ```ubuntu:bionic``` one use the bionic version of the deb?

I just noticed that the Launchpad PPA uses the same underlying kernel for all builds (e.g. xenial and bionic), and not the kernel of the target Ubuntu release. This might be a problem since ```raft```'s source is kernel-dependent and compilation changes according to the host's kernel version.

I'll probably need to come up with something around compilation.

In the meantime, if you build ```raft``` from sources on kernel X.Y on Ubuntu Z and then deploy it on the same system or a system with matching kernel and Ubuntu version, that should work. Please let me know if that's not the case for you.

**Comment by paulstuart** [comment]
I'm running this on a mac -- the kernel is: 

`Linux 577035ae604e 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

dpkg -s shows the respective versions:

`Version: 1.1.0-0~201911041041~ubuntu16.04.1`

`Version: 1.1.0-0~201911041041~ubuntu18.04.1`

I'll need to get a VM going to stare and compare on building directly from source, so that can wait (and it doesn't seem necessary considering your guidance). I'll consider the matter resolved and you can close this issue when you see fit.
