### ISSUE TITLE
Assertion failed: rc == 0 (src/leader.c: leader__close: 257)

### ISSUE THREAD

**Issue by ibuildthecloud** [canonical/dqlite#194]
On startup/restart of a failed node I randomly get this assertion and then the node will go into a restart loop always failing with this assertion.  I'm going to see if I can put together something reproducible for this issue, but I was first curious if there was any theories as to when/how this could happen?

**Comment by freeekanayaka** [comment]
It means that for some reason there are still outstanding SQLite resources (such as prepared statements) being held and not having being closed. This is probably not a show stopper and that assertion **could** be downgraded to some sort of warning. However, since the dqlite code should take care of cleaning up everything before getting to that line, there's definitely some unexpected scenario in play that would be nice to understand and fix.
