### ISSUE TITLE
License info on home page is incorrect

### ISSUE THREAD

**Issue by mjmac** [canonical/dqlite#215]
On https://dqlite.io, the license is listed as "Published under the Apache 2.0 license for maximum compatibility." However, as of commit fe0fbed, it appears that the license is now LGPL3.

**Comment by stgraber** [comment]
Ah yeah, the website needs to get updated...

@freeekanayaka

**Comment by stgraber** [comment]
Worth noting that on the compatibility front, we're pretty much identical as it's LGPLv3 with a static linking exception.

**Comment by mjmac** [comment]
FWIW, If I wanted to use this in a project at $BIGCORP, I'd have a very hard time getting signoff on anything \*GPL\*, with or without a linking exception.

**Comment by stgraber** [comment]
@mjmac you're not allowed to use the C library? :)

I understand restrictions for the GPL, but LGPL by design doesn't have any of the downstream licensing side-effects and is why it's absolutely suitable for a library. It can be used in any project without it impacting the license of the project.

Anyway, it's policy on our side to release under GPL/LGPL unless we get a specific exception so licensing isn't really up to us.
