### ISSUE TITLE
How can I init a three-node cluster and share the same db in C?

### ISSUE THREAD

**Issue by su7811659** [canonical/dqlite#238]
I'm new here, I just finish building the library of dqlite, but I was stuck in creating a cluster with three nodes.
How could I implement a simple example in C ? Thanks

**Comment by su7811659** [comment]
> I'm new here, I just finish building the library of dqlite, but I was stuck in creating a cluster with three nodes.
> How could I implement a simple example in C ? Thanks

**Comment by freeekanayaka** [comment]
There's currently no wire-level dqlite client written in C, which you need in order to form a cluster (since you'll have to use the wire protocol to add new nodes).

I recommend using the [go-dqlite bindings](github.com/canonical/go-dqlite/), in particular look at the [demo application](https://github.com/canonical/go-dqlite/blob/master/cmd/dqlite-demo/dqlite-demo.go) there to get started quickly.

If using Go is not an option for you, which language are you targeting? The dqlite wire protocol is documented [here](https://dqlite.io/docs/protocol) and you could write a client for your language. Unfortunately at the moment we don't plan to add other clients ourselves, but contributions would be welcome.
