### ISSUE TITLE
DQlite on JFFS2

### ISSUE THREAD

**Issue by daanpape** [canonical/dqlite#271]
I read in the docs that DQlite configures DQlite to be in WAL mode. This is not possible on a JFFS2 file system. Is this an absolute requirement?

Another question that I have is the following. Is it possible to set up a 2 node cluster or are you required to use 3 nodes to reach a quorum?

Kind regards,
Daan

**Comment by freeekanayaka** [comment]
Dqlite swaps SQLite's default [sqlite3_vfs](https://www.sqlite.org/vfs.html) implementation with a [custom one](https://dqlite.io/docs/replication) which lives entirely in memory. Therefore WAL mode can be used regardless of the underlying file system.

It is possible to set up a 2 node cluster, but in terms of availability that'd be **worst** than a one node cluster. If you have two independent and unclustered plain SQLite nodes and you lose one of them, the other will do just fine. If you have two clustered Dqlite nodes and you lose one, the other will be unavailable too (because it will lack quorum).

For any practical use, I'd say 3 is the minimum.

**Comment by daanpape** [comment]
Thank you for the fast and clear answer.
