### ISSUE TITLE
Requests take longer than usual

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/dqlite#284]
When applying load there are often requests that take much longer than expected. In the attached reproducer we are doing consecutive write requests of about 4k payload and we print the time each one takes to complete. Usually each write operation takes some milliseconds but there are requests that spike to seconds. I couldn't pinpoint the issue anywhere in dqlite's code but this behavior could be caused by some library used. Have you noticed this before? Do you suspect anything that might be causing this? Thanks.

Here is a example run.
```
....
Wrote key 11006 in 17 milisecs
Wrote key 11007 in 43 milisecs
Wrote key 11008 in 16 milisecs
Wrote key 11009 in 16 milisecs
Wrote key 11010 in 15 milisecs
Wrote key 11011 in 17 milisecs
Wrote key 11012 in 21 milisecs
Wrote key 11013 in 25 milisecs
**Wrote key 11014 in 1404 milisecs**
Wrote key 11015 in 8 milisecs
Wrote key 11016 in 17 milisecs
Wrote key 11017 in 18 milisecs
Wrote key 11018 in 11 milisecs
Wrote key 11019 in 19 milisecs
Wrote key 11020 in 14 milisecs
.....
```

[p2.patch.gz](https://github.com/canonical/dqlite/files/5940351/p2.patch.gz)
[delay-reproducer.sh.gz](https://github.com/canonical/dqlite/files/5940352/delay-reproducer.sh.gz)

**Comment by MathieuBordere** [comment]
This seems to be related with the raft nodes ignoring AppendEntries RPC's when they are taking a snaphot. [1]
Normally, upon the next `HeartBeat` timeout, the entries would be resent, but the problem is aggravated due to [2], because of the optimistic `next_index` update, it will take an additional HeartBeat timeout to send the entries.

The HeartBeat timeout in `dqlite` is set too 500ms [3] which is pretty much, that's why you are experiencing those long timeouts.
You could lower the HeartBeat timeout in `dqlite` by calling [3], but I should still update that function to also set the snapshot_install_timeout which acts like a -hacky- heartbeat timeout when installing a snapshot on another node. [4]

I'm currently implementing the TODO in [1] to fix the issue.

[1] https://github.com/canonical/raft/blob/1685cf4ea47a697000337717a96a6b75cfff8c78/src/recv_append_entries.c#L115
[2] https://github.com/canonical/raft/blob/1685cf4ea47a697000337717a96a6b75cfff8c78/src/replication.c#L130
[3] https://github.com/canonical/dqlite/blob/a89301a62e902df22e45649722a31bf1fbd6857a/src/server.c#L287
[4] https://github.com/canonical/raft/issues/179

**Comment by MathieuBordere** [comment]
@freeekanayaka https://github.com/canonical/raft/blob/1685cf4ea47a697000337717a96a6b75cfff8c78/src/recv_append_entries.c#L115 This is the code that ignores appendEntries RPC when a node is taking or installing a snapshot. I agree that ignoring the entries while installing the snapshot is probably a good idea, but was it also the idea to ignore entries while taking a snapshot? Because the comment only talks about ignoring entries when installing a snapshot.

**Comment by freeekanayaka** [comment]
> @freeekanayaka https://github.com/canonical/raft/blob/1685cf4ea47a697000337717a96a6b75cfff8c78/src/recv_append_entries.c#L115 This is the code that ignores appendEntries RPC when a node is taking or installing a snapshot.
> 
> I agree that ignoring the entries while installing the snapshot is probably a good idea, but was it also the idea to ignore entries while taking a snapshot? The comment only talks about ignoring entries when installing a snapshot and things 'just work' when I accept AppendEntries RPCs while taking a snapshot and the longer request duration doesn't occur.
> 
> Will inspect code and add more tests to make sure it's actually fine to change this, just wanted to know if it was intentional.

No, the idea was to ignore AppendEntries RPCs just when installing a snapshot, not when taking it. The reason is that installing a snapshot possibly means also truncating the on-disk log so it's harder to do that and also deal with new AppendEntries.
