### ISSUE TITLE
Investigate use of https://sqlite.org/c3ref/busy_handler.html to handle SQLITE_BUSY

### ISSUE THREAD

**Issue by MathieuBordere** [canonical/dqlite#293]
Hi @freeekanayaka, was https://sqlite.org/c3ref/busy_handler.html ever looked into to automatically handle `SQLITE_BUSY` return codes?

**Comment by freeekanayaka** [comment]
> Hi @freeekanayaka, was https://sqlite.org/c3ref/busy_handler.html ever looked into to automatically handle `SQLITE_BUSY` return codes?

Yeah but that doesn't really help. Beside the fact that in order to be effective you'd basically have to sleep in your busy handler callback (which is what the default busy handler sported by SQLite itself does) and we can't actually sleep because we're in a non-blocking event loop, even if you implemented server-side retries triggering after the active write transaction has finished, your retried transaction would likely fail again with [`SQLITE_BUSY_SNAPSHOT`](https://sqlite.org/rescode.html#busy_snapshot) and at that point the only sensible thing to do would be to trash the transaction and ask the client to start over. Considering that, it's better to ask the client itself to retry in the first place.

**Comment by MathieuBordere** [comment]
Okay, thanks for clarifying!
