### ISSUE TITLE
Cluster freezes during checkpoints

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/dqlite#305]
During a checkpoint the cluster fails to serve requests. Currently we handle such cases with retries.

Do we know how long a checkpoint takes? How long should we retry? How often do we checkpoint? Seems to happen often in the K8s use case.

**Comment by MathieuBordere** [comment]
Sorry, for the (extremely) late response. In previous versions of dqlite, checkpoints were coordinated cluster-wide, and were only finished when all members of the cluster were done checkpointing. Since version v1.10.0, nodes checkpoint individually, which should lower the amount of time that the leader is unavailable due to a checkpoint. Hope it has a meaningful impact, will close for now.
