### ISSUE TITLE
no such function: json_extract

### ISSUE THREAD

**Issue by pycaster** [canonical/dqlite#306]
Hi

In my application I am trying to use a query that requires json extension. I verified this query with sqlite3 but doesn't seem to find the function with dqlite coming from standard deb pkg. 

Here is a test I did with go-dqlite on the database 

```
dqlite> SELECT json_extract(meta,  '$.uuid') from objects;
Error:  query: no such function: json_extract
```

Is this the correct way to configure dqlite with the extension enabled? This dint work either.

```
SQLITE_CFLAGS='-DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1' ./configure
```

What am I missing? Thanks.

**Comment by pycaster** [comment]
Should dqlite even parse sql queries? Why does this error happen?

**Comment by pycaster** [comment]
ugh my application wasn't build with `-tags libsqlite3`. Damn this took me all day to figure. I couldn't find any file that's using this build tag. What does `-tags` doing?

**Comment by stgraber** [comment]
It instructs `go-sqlite3` (mattn/go-sqlite3) to build against the sqlite3 shared library instead of using an embedded static copy of the code. You won't find any reference of this tag within go-dqlite as go-dqlite works either way, it's up to you to decide if you want the embedded copy or shared library copy just as it is when you do normal sqlite3 from Go.

**Comment by stgraber** [comment]
https://github.com/mattn/go-sqlite3#linux

**Comment by pycaster** [comment]
Ahh forgot about `mattn/go-sqlite3`. Thanks.
