### ISSUE TITLE
No documentation for dqlite roles

### ISSUE THREAD

**Issue by andrewchambers** [canonical/dqlite#369]
Forgive me if I have missed it, but there seems to be no documentation about what the valid node roles are and how they behave.

**Comment by MathieuBordere** [comment]
`Voter`, `Spare` and `StandBy` refer to the raft [roles](https://github.com/canonical/raft/blob/78b79370f9a0c192513c40185fe5f54b2ef968e0/include/raft.h#L88)

Unfortunately, due to a historic artifact, the number codes of the roles are not the same in [dqlite](https://github.com/canonical/dqlite/blob/35b5418af73d5112c156d05eec2ad85268707cb3/src/protocol.h#L11) and raft.

I agree, documentation is lacking, it is something that we will work on in the near future.
