### ISSUE TITLE
Question/Documentation: How does dqlite handle 'begin immediate' ?

### ISSUE THREAD

**Issue by andrewchambers** [canonical/dqlite#370]
In normal sqlite3 you can force the immediate acquisition of a write lock via 'begin immediate', Is this possible in dqlite? If it is possible, does this guarantee any reads in the immediate transaction occur through the leader?

**Comment by MathieuBordere** [comment]
Technically, there's no reason why it wouldn't work, I haven't tested it yet TBH.
In dqlite all reads and writes go through the leader, the replica's are just there to replace the leader and don't serve requests. So yes, all reads in that transaction will go through the leader. If leadership is lost in the middle of the transaction, the transaction is aborted.

**Comment by andrewchambers** [comment]
Ah I see, the documentation says that dqlite may have stale reads in the 'consistency model' section - so I wondered if doing an immediate transaction might avoid that. Am I misunderstanding the consistency model?

**Comment by andrewchambers** [comment]
I suppose another possibility is that a 'begin immediate;' transaction that does not do any WAL updates might not trigger the raft update?

**Comment by MathieuBordere** [comment]
> Ah I see, the documentation says that dqlite may have stale reads in the 'consistency model' section - so I wondered if doing an immediate transaction might avoid that. Am I misunderstanding the consistency model?

There is an explanation in the [Consistency Model](https://dqlite.io/docs/consistency-model).

> However, stale reads are rare in practice. They can happen only in case a read transaction is started on a leader that was disconnected from a majority of voting nodes but that didn’t yet realize it and didn’t yet step down from leader. If in the meantime another leader was elected by the rest of the voting nodes and that leader committed a write transaction before the old leader started serving the read transaction, then that read transaction might observe stale data, since read transactions are served by a leader without making sure that it is actually still the leader and hence no write transaction might have happened before (so called “quorum reads”).
> 
> In case a stale reads actually occurs, the data observed by the read transaction can’t be arbitrarily old. A disconnected leader will take at most an election timeout to realize it’s not leader anymore, therefore the data it serves can be at most a few hundred milliseconds old (with default Dqlite settings).

**Comment by MathieuBordere** [comment]
Yes, we indeed only offer the 'weak' reads.

**Comment by freeekanayaka** [comment]
I didn't test `BEGIN IMMEDIATE` either, but I believe the only effect it would have is that it would acquire the write lock right away so you can be sure you won't get any `SQLITE_BUSY` error after that (since no other transaction will be able to acquire the write lock).

Regarding strong/weak reads, also note that the SQL model is general is built around weak reads (serializable transactions), because strong reads don't make much sense in the way SQL is typically used (client reads data, takes some decisions, writes some data back).

**Comment by freeekanayaka** [comment]
Just for extra clarity, note also that even in a "weak" model where stable reads are possible, it's not possible to actually make changes based on those stale reads: if you run a `SELECT` returning some stale value (i.e. a value that in the meantime has been changed by a concurrent transaction that performed a commit) then take some decision based on that value and issue some write statements (`INSERT` or `UPDATE`) your transaction will fail to commit because it would violate serializability (I believe the error returned in that case would be `SQLITE_SNAPSHOT_BUSY`).

**Comment by freeekanayaka** [comment]
I realized there is actually a way to have strong reads in dqlite, basically doing the same as rqlite does, but at the user level.

If you want to be sure that you are reading the most recent version of a value, you can use a normal `BEGIN` immediately followed by some database-changing write (e.g. incrementing a counter with an `UPDATE`), then performing the read you are interested in and finally issuing a `COMMIT`.

If the transaction succeeds you are guaranteed that the value that was returned was the most recent one at the time the read was done (linearizability aka strong read), because if some other local transaction had changed it (e.g. in the time between the initial `BEGIN` and the `UPDATE`) or if the leader had lost leadership during the transaction then the final `COMMIT` statement would fail.

This essentially the same as rqlite's approach for running the read through consensus (which is the usual approach for achieving linearizablity/strong-reads in Raft-based systems).

The `BEGIN IMMEDIATE` statement could be used as an optimization in order to fail earlier (in case there's already a local concurrent writer), but it's not required for this approach to work.

@MathieuBordere perhaps this trick could be added to the documentation in case somebody needs strong reads.

**Comment by andrewchambers** [comment]
I definitely think adding it to the consistency model documentation would be nice - it removes a perceived limitation that might have put some users off.
