### ISSUE TITLE
REQUEST_CLUSTER documentation is inaccurate re its parameter

### ISSUE THREAD

**Issue by FGasper** [canonical/dqlite#400]
The “List all nodes of the cluster” request’s documentation says that its uint64 argument is unused. However, the server _does_ use that to differentiate whether to return the role code as part of the node-info structure.

A client would, on reading that the uint64 argument is unused, leave it at 0. But that will cause the returned node-info structure to omit the role code, which mismatches the node-info documentation.

The documentation should be amended either to say that DQLITE_REQUEST_CLUSTER’s argument should always be 1, or that node-info depends on the format code given as part of the request.

Also, ideally, should there be an indicator in the DQLITE_RESPONSE_SERVERS header of which node-info version is part of the message body? I couldn’t see anything, but this seems like it’d be helpful to have.

**Comment by cole-miller** [comment]
Hi Felipe! The dqlite.io documentation is out of date in a number of places -- we're planning to overhaul and comprehensively update it in the future, but in the meantime we're happy to address individual points like this.

> The documentation should be amended either to say that DQLITE_REQUEST_CLUSTER’s argument should always be 1, or that node-info depends on the format code given as part of the request.

I've updated the documentation of the CLUSTER request to note that the format field should always be set to 1. There's still the question of interoperation with servers running old versions of dqlite (v1.3.0, from January 2020, is the first release to include this change), since these servers will always return node-info in the old format. I'm not sure what kind of documentation/guarantees we want to provide around that -- @freeekanayaka, any thoughts?

**Comment by freeekanayaka** [comment]
Unfortunately we can't change old servers, but one option would be to modify current code so it returns an error if  it gets a request about a version it doesn't know of. This should future-proof it.

**Comment by FGasper** [comment]
I’m going to close this as the documentation issue reported is resolved.

Thank you!
