### ISSUE TITLE
Systematically avoiding overflow for integer operations

### ISSUE THREAD

**Issue by cole-miller** [canonical/dqlite#467]
@MathieuBordere suggested that we should have some code (probably macros?) in dqlite/raft to perform arithmetic without silent wrapping/overflow, and I agree. One of the crashes I found with afl (#465) can be triggered by an overflow in the multiplication here, e.g.:

https://github.com/canonical/dqlite/blob/e618e62985de2f8d584ef2902977b2ed00ce9d19/src/conn.c#L165

**Comment by freeekanayaka** [comment]
In the specific case that is mentioned, I think that the value of `c->requests.words` should be checked at the time the request received by the server from the client over the wire gets decoded, basically right after this line:

https://github.com/canonical/dqlite/blob/e618e62985de2f8d584ef2902977b2ed00ce9d19/src/conn.c#L194

Validating the values that the client sends us over the wire is something we probably don't always do, so it'd be nice to check that too.

I'm not entirely sure what macros can do in a case like the mentioned one, what would the macro do?

**Comment by freeekanayaka** [comment]
The drawback I see is that it's difficult to understand what went wrong, because the check does not happen when the user provides the input, but at some point later down the road, so it'd be difficult to produce a meaningful error message (e.g. "invalid message words count: %d", to stick with the mentioned example).

Given that input should be ideally validated, I'd suggest to do check all our assumptions as soon as user input is received. After that point we can safely assume that those assumptions are met (e.g. the words count is not greater than X). Note that there might be other types of issues related to invalid user input that don't fall under the overflow category, so it feels to me that anyway the generic solution would be to validate the input. That should cover the overflow problem and any other ones where we make some sort of assumption on the input.

**Comment by freeekanayaka** [comment]
Note also that placing individual assertions about the individual arguments of a multiplication just before the multiplication takes place helps in identifying what exactly is wrong, as opposed to just checking the result of the multiplication, in which case you don't know what factor is to blame. This is probably irrelevant for the specific case that was outlined about, for the words count (since one of the two factors is a constant), but it might be true in general.
